services:
 web:
   build: .
   working_dir: /data
   command: python aulabd.py
   links:
    - db
   volumes:
    - .:/data
   ports:
    - "5008:5008"

 db:
  image: mysql:5.7
  environment:
      MYSQL_ROOT_PASSWORD: edher123
  ports:
    - "3309:3309"
